export const GOOGLE_FONTS = [
  "Roboto", "Open Sans", "Lato", "Montserrat", "Oswald", "Source Sans Pro", "Raleway", "PT Sans", 
  "Merriweather", "Ubuntu", "Lora", "Playfair Display", "Nunito", "Roboto Mono", "Muli", "Arimo", 
  "Quicksand", "Josefin Sans", "Libre Baskerville", "Anton", "Archivo Narrow", "Dancing Script", 
  "Pacifico", "Lobster", "Indie Flower", "Satisfy", "Courgette", "Great Vibes", "Kaushan Script", 
  "Cookie", "Allura", "Sacramento", "Yellowtail", "Grand Hotel", "Marck Script", "Rouge Script",
  "Homemade Apple", "Alex Brush", "Pinyon Script", "Arizonia", "Petit Formal Script", "Herr Von Muellerhoff",
  "Parisienne", "Tangerine", "Clicker Script", "Bad Script", "Calligraffitti", "Cedarville Cursive",
  "Covered By Your Grace", "Damion", "Euphoria Script", "Fondamento", "Give You Glory", "Gloria Hallelujah",
  "Gochi Hand", "Handlee", "Just Another Hand", "Kristi", "La Belle Aurore", "Loved by the King",
  "Meddon", "Megrim", "Montez", "Mr Dafoe", "Mr De Haviland", "Mrs Saint Delafield", "Nanum Pen Script",
  "Nothing You Could Do", "Over the Rainbow", "Permanent Marker", "Rancho", "Reenie Beanie", "Rock Salt",
  "Shadows Into Light", "Shadows Into Light Two", "Stalemate", "Sue Ellen Francisco", "The Girl Next Door",
  "Waiting for the Sunrise", "Zeyada", "Maven Pro", "Exo", "Exo 2", "Orbitron", "Audiowide", "Michroma",
  "Rajdhani", "Teko", "Chakra Petch", "Kanit", "Tinos", "Arvo", "Bitter", "Bree Serif", "Crimson Text",
  "Domine", "EB Garamond", "Noticia Text", "Old Standard TT", "PT Serif", "Playfair Display SC",
  "Rokkitt", "Vlasic", "Vollkorn", "Zilla Slab", "Abril Fatface", "Alfa Slab One", "Bangers", 
  "Bowlby One SC", "Carter One", "Chivo", "Comfortaa", "Creepster", "Fascinate", "Faster One", 
  "Fredoka One", "Fugaz One", "Graduate", "Greekish", "Limelight", "Luckiest Guy", "Monoton", 
  "News Cycle", "Notable", "Passion One", "Patua One", "Paytone One", "Press Start 2P", 
  "Righteous", "Ruslan Display", "Sigmar One", "Special Elite", "Squada One", "Syncopate", 
  "Unica One", "VT323", "Wallpoet", "Almendra", "Amita", "Balthazar", "Belgrano", "Berkshire Swash", 
  "Cinzel", "Cinzel Decorative", "Copse", "Cormorant", "Cormorant Garamond", "Eczar", "Fjord One", 
  "Gilda Display", "Habibi", "Inknut Antiqua", "Italiana", "Judson", "Jura", "Kurale", 
  "Lusitana", "Mate", "Mate SC", "Modern Antiqua", "Neuton", "Oranienbaum", "Ovo", "Piazzolla", 
  "Poly", "Prata", "Providencia", "Ranga", "Rasa", "Ritchy", "Sahitya", "Salsa", "Santiarka", 
  "Sawarabi Mincho", "Slabo 13px", "Slabo 27px", "Sorts Mill Goudy", "Spectral", "Sree Krushnadevaraya", 
  "Sumana", "Sura", "Suranna", "Suravaram", "Trirong", "Trocchi", "Trykker", "Ultra", 
  "Unna", "Vesper Libre", "Vidaloka", "Volkhov", "Yibi", "Abel", "Alegreya", "Alegreya Sans", 
  "Amiri", "Asap", "Assistant", "Barlow", "Cairo", "Catamaran", "Dosis", "Fira Sans", 
  "Heebo", "Hind", "IBM Plex Sans", "Inconsolata", "Inter", "Josefin Sans", "Karla", 
  "Libre Franklin", "Manrope", "Mukta", "Nanum Gothic", "Noto Sans", "Padauk", "Pattaya", 
  "Questrial", "Rubik", "Sarabun", "Signika", "Staatliches", "Tajawal", "Varela Round", "Work Sans",
  "Yantramanav"
];
